### ISSUE TITLE
"Invalid Monitor Handle" after changing screen configuration

### ISSUE THREAD

**Issue by j10k** [artem78/AutoScreenshot#15]
**Describe the bug**
I have set AutoScreenshot to capture a screenshot of all monitors. After switching monitors, e.g. by connecting to a dock, subsequent screenshots fail with "Invalid Monitor Handle". Additionally, the "Used monitor" dropdown in the configuration dialogue is disabled/greyed out and set to "monitor 1". Restart fixes the problem

**To Reproduce**
1. Enable auto capture of all monitors
2. Change monitor configuration. Note that this does not occur for all changes, even when the same monitors are used
3. At the next time interval, an error box saying "Invalid Monitor Handle" appears in the background.
4. Upon opening the config dialog, observe that the Used monitor dropdown is greyed out.

**Expected behavior**
AutoScreenshot should handle changes in the monitor configuration and update the monitor handles after changes.

**Screenshots**
n/a

**Version**
1.7.1

**Additional context**
Here's my config.ini
```
[main]
OutputDir=C:\Users\placeholder\Pictures\AutoScreenshots\
ImageFormat=PNG
JPEGQuality=80
ColorDepth=24
Language=en
Monitor=-1
Counter=1824
CounterDigits=6
FileNameTemplate=%Y-%M-%D\%H.%N.%S
StopWhenInactive=1
StartCaptureOnStartUp=1
StartMinimized=1
AutoRun=1
```

**Comment by artem78** [comment]
Can't reproduce on Notebook with Windows 7 and plugged additional monitor. I tried:
- connect/disconnect extended monitor
- change orientation
- change primary monitor
- change order

Could you please describe your monitor configuaration and what action causes a problem? Take screenshots and maybe video also may be useful.

I only saw that program doesn't update listbox when monitor configuration has been changed.

**Comment by artem78** [comment]
Fixed in v1.8

**Comment by j10k** [comment]
Thank you! I was wondering how to provide debug information, and will reopen this issue if it persists.

**Comment by j10k** [comment]
Hi, unfortunately the issue is only partially fixed for me (not sure whether to reopen the issue here or open a new one): I have set AutoScreenshot to screenshot all monitors. After changing the display configuration, however, the configuration reverts to "primary monitor". The expected behaviour would be to keep screenshotting all monitors.

**Comment by artem78** [comment]
> not sure whether to reopen the issue here or open a new one

It will be better to create new one.

**Comment by artem78** [comment]
> After changing the display configuration, however, the configuration reverts to "primary monitor".

You can change it manually.

**Comment by artem78** [comment]
I fixed behavior. Check this build: [AutoScreenshot 78c826a7 test build.zip](https://github.com/artem78/AutoScreenshot/files/7231587/AutoScreenshot.78c826a7.test.build.zip)

**Comment by j10k** [comment]
I can confirm that this issue is fixed. Thank you!

**Comment by artem78** [comment]
Added in [1.8.1 release](https://github.com/artem78/AutoScreenshot/releases/tag/v1.8.1)
